### ISSUE TITLE
SSAS 2017

### ISSUE THREAD

**Issue by ArmanFalah** [msornakumar/BISM-SSAS-Tabular-Documentation-Tool#9]
Hi again,

Does it support SSAS 2017?

I got this error
![image](https://user-images.githubusercontent.com/24508605/45594169-6764b700-b9ab-11e8-840e-a08d4144c112.png)

**Comment by msornakumar** [comment]
Hi ,

  Yes this tool supports 2017 as well. Can you please paste the complete error message from the progress textbox. That will be very helpful for analysis.

Thanks

Sorna

**Comment by ArmanFalah** [comment]
Hi Sorna

------
 Generation started....
Database Compatibility Level - 1400
TOM Extracting Metadata for olap - Tezlabs_Nemoudar
--------------------------------------------------------------------------------------
Error Occured
--------------------------------------------------------------------------------------
System.Runtime.InteropServices.COMException (0x80040154): Retrieving the COM class factory for component with CLSID {00024500-0000-0000-C000-000000000046} failed due to the following error: 80040154 Class not registered (Exception from HRESULT: 0x80040154 (REGDB_E_CLASSNOTREG)).
   at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean noCheck, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Boolean& bNeedSecurityCheck)
   at System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
   at System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
   at System.Activator.CreateInstance(Type type, Boolean nonPublic)
   at System.Activator.CreateInstance(Type type)
   at BISMDocumenterTOM.BISMDocumenterCls.GenerateDocument(String ServerName, String DBName, String CubeName, String DocumentPath, String FileName, TextBox progressTextBox, Boolean OpenXl)
--------------------------------------------------------------------------------------
Error Occured
--------------------------------------------------------------------------------------
System.NullReferenceException: Object reference not set to an instance of an object.
   at System.Runtime.InteropServices.Marshal.ReleaseComObject(Object o)
   at BISMDocumenterTOM.BISMDocumenterCls.GenerateDocument(String ServerName, String DBName, String CubeName, String DocumentPath, String FileName, TextBox progressTextBox, Boolean OpenXl)
   at SSASDocumentationTool_DescriptionEditor.frmSSASDocumentationTool.cmdGenerateDocument_Click(Object sender, EventArgs e)

**Comment by msornakumar** [comment]
Thanks for sharing. Looking into this.

One more question is , are you running this tool on top of a multidimensional model ?

If that is the case , This tool as of now supports only the tabular models.

**Comment by ArmanFalah** [comment]
No I am running this on tabular server. My tabular database has translations, don’t you think this is the problem?

**Comment by msornakumar** [comment]
Hi Arman ,
  This issue seems to be caused by the excel configuration in the machine.

  on quick internet search found the below relevant thread. Can you please try the solution in it

https://social.msdn.microsoft.com/Forums/en-US/b6388275-b295-4e55-8c25-6d8788eac1ca/error-while-creating-excel-object?forum=Vsexpressvb

  Regarding translations , will try to update the tool ASAP to support that.

Thanks

Sorna
